### ISSUE TITLE
Output: Kafka

### ISSUE THREAD

**Issue by samcm** [ethpandaops/xatu#211]
Create a new output in `pkg/output` that connects to a Kafka cluster and publishes events on to a topic. The output can make use of the `proto/xatu.Filter` struct to handle event routing.

**Comment by samcm** [comment]
@0x-dx Hello! That'd be awesome, thank you!

**Comment by 0x-dx** [comment]
@samcm Currently I have added a drafted version at https://github.com/ethpandaops/xatu/pull/239. Probably will perform some more testing this weekend, before pushing the final changes along with the documentation. Meanwhile, any feedback would be appreciated.

**Comment by samcm** [comment]
That's looking really really good @0x-dx - nice work! Let me know when you've pushed those changes and are happy for me to merge 🙏

**Comment by 0x-dx** [comment]
@samcm I have pushed the remaining changes to #239. It can be reviewed.

**Comment by samcm** [comment]
Merged! Nice work 🎉
